# Hugo root config file
baseURL: https://www.frasermclean.com/
title: Fraser McLean
languageCode": en-AU
defaultContentLanguage: en
enableGitInfo: true
enableRobotsTXT: true
titleCaseStyle: none
theme: stack

pagination:
  disableAliases: false
  pagerSize: 5
  path: page

permalinks:
  post: /post/:year/:month/:slug/
  page: /:slug/
