social:
  - identifier: github
    name: GitHub
    url: https://github.com/frasermclean
    weight: 1
    params:
      icon: brand-github
  - identifier: linkedin
    name: LinkedIn
    url: https://www.linkedin.com/in/frasermclean/
    weight: 2
    params:
      icon: brand-linkedin
  - identifier: instagram
    name: Instagram
    url: https://www.instagram.com/frasermclean81/
    weight: 3
    params:
      icon: brand-instagram
  - identifier: twitter
    name: Twitter
    url: https://twitter.com/frasermclean81
    weight: 4
    params:
      icon: brand-twitter
  - identifier: rss
    name: RSS
    url: /index.xml
    weight: 5
    params:
      icon: rss
