main:
  - identifier: home
    name: Home
    url: /
    weight: 1
    params:
      icon: home
  - identifier: about
    name: About Me
    url: /about/
    weight: 2
    params:
      icon: user

social:
  - identifier: github
    name: GitHub
    url: https://github.com/frasermclean
    weight: 1
    params:
      icon: brand-github
  - identifier: linkedin
    name: LinkedIn
    url: https://www.linkedin.com/in/frasermclean/
    weight: 2
    params:
      icon: brand-linkedin
  - identifier: instagram
    name: Instagram
    url: https://www.instagram.com/frasermclean81/
    weight: 3
    params:
      icon: brand-instagram
