favicon: /favicon.ico
dateFormat:
  published: 2 January 2006
  lastUpdated: 2 January 2006

# Pages placed under these sections will be shown on homepage and archive page.
mainSections:
  - post

sidebar:
  subtitle: Adventures in the world of software development
  avatar:
    enabled: true
    local: true
    src: /images/avatar.png

widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc

comments:
  enabled: true
  provider: remark42
  remark42:
    host: https://comments.frasermclean.com
    site: frasermclean
    locale: en

footer:
  since: 2023
  customText: >-
    The complete source code for this site can be found on
    <a href="https://github.com/frasermclean/personal-site" target="_blank">GitHub</a>
