name: personal-site-deps

services:
  # Azure Storage Emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - azurite-data:/data
      - ./localhost.pem:/certs/localhost.pem
      - ./localhost-key.pem:/certs/localhost-key.pem
    command:
      - azurite
      - --blobHost
      - '0.0.0.0'
      - --queueHost
      - '0.0.0.0'
      - --tableHost
      - '0.0.0.0'
      - --location
      - /data
      - --oauth
      - basic
      - --cert
      - /certs/localhost.pem
      - --key
      - /certs/localhost-key.pem

volumes:
  azurite-data:
    driver: local
