comments:
  enabled: true
  provider: giscus
  giscus:
    repo: frasermclean/personal-site
    repoID: R_kgDOKbrs5Q
    category: General
    categoryID: DIC_kwDOKbrs5c4CnAse
    mapping: pathname
    strict: 1
    lightTheme: noborder_light
    darkTheme: noborder_dark
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    lang: en

turnstile:
  siteKey: 0x4AAAAAAAhX2PdPqj0Cojk1
