name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: main
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

env:
  ARTIFACT_NAME: app

jobs:
  # Build job
  build-app:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      # Install build dependencies
      - name: Install Hugo
        run: |
          sudo snap install hugo
          sudo snap install dart-sass

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
          fetch-depth: 0

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: '[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true'
        working-directory: ${{ github.workspace }}/src

      # Build Hugo site
      - name: Build Hugo site
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --gc --minify
        working-directory: ${{ github.workspace }}/src

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/src/public

  deploy-infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy template
      - uses: azure/arm-deploy@v1
        name: Deploy template
        with:
          scope: resourcegroup
          resourceGroupName: frasermclean-site-rg
          template: ${{ github.workspace }}/deploy/main.bicep
          parameters: ${{ github.workspace }}/deploy/main.bicepparam

  # Deployment job
  deploy-app:
    name: Deploy app
    environment:
      name: main
    runs-on: ubuntu-latest
    needs:
      - build-app
      - deploy-infra
    env:
      APP_PATH: ${{ github.workspace }}/artifact
    steps:
      # Download artifact from build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.APP_PATH }}

      # Deploy to Azure Static Web Apps
      - uses: azure/static-web-apps-deploy@v1
        name: Deploy application
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
          app_location: ${{ env.APP_PATH }}
          skip_app_build: true
          skip_api_build: true
