name: Deploy infrastructure

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-infra.yaml
      - deploy/**
      
  workflow_dispatch:

jobs:
  deploy-infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: main
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: main
      cancel-in-progress: false
    steps:
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy template
      - uses: azure/arm-deploy@v1
        name: Deploy template
        env:
          ATTEMPT_ROLE_ASSIGNMENTS: false
        with:
          scope: resourcegroup
          resourceGroupName: frasermclean-site-rg
          template: ${{ github.workspace }}/deploy/main.bicep
          parameters: ${{ github.workspace }}/deploy/main.bicepparam
