name: Build and deploy backend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-backend.yaml
      - backend/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/deploy-backend.yaml
      - backend/**

env:
  ARTIFACT_NAME: functions-backend-${{ github.run_number }}-${{ github.run_attempt}}

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

        # Restore NuGet packages
      - name: Restore packages
        run: dotnet restore

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      # Publish project
      - name: Publish project
        run: >-
          dotnet publish
          --no-restore
          --configuration Release
          --output publish
        working-directory: ${{ github.workspace }}/backend

        # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/backend/publish

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    environment: main
    steps:
      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        id: download-artifact
        with:
          name: ${{ env.ARTIFACT_NAME }}

      # Deploy to Functions app
      - name: Deploy to Functions app
        uses: Azure/functions-action@v1
        with:
          app-name: frasermclean-site-func
          package: ${{ steps.download-artifact.outputs.download-path }}
          publish-profile: ${{ secrets.FUNCTIONS_PUBLISH_PROFILE }}
